[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
two_sided_marketplace_for_services = "4GVYCsgaxtqHW61wddpKtthbFZqvXhREghgE9C45YV7w"

[programs.devnet]
two_sided_marketplace_for_services = "4GVYCsgaxtqHW61wddpKtthbFZqvXhREghgE9C45YV7w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
