[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
two_sided_marketplace_for_services = "EQY5RoA9unEGkvY8DQVK5v7qq1AMHKSKNQmrkQ39wmFb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
